CUDA_VISIBLE_DEVICES=0 nohup python -u finetune_sup_head_regression.py esm1b_t33_650M_UR50S ~/clean_datasets/S/S_target sup --include mean per_tok --toks_per_batch 2048 --num_classes 5 --idx S --lr 2e-2 --split_file ~/clean_datasets/S/S_target.pkl --seed 1 --wandb-name 0510_Sr_adv_5e-7_seed1_GPU2 --adv --gamma 5e-7  > 0510_Sr_adv_5e-7_seed1_GPU0.out &

CUDA_VISIBLE_DEVICES=1 nohup python -u finetune_sup_head_regression.py esm1b_t33_650M_UR50S ~/clean_datasets/S/S_target sup --include mean per_tok --toks_per_batch 2048 --num_classes 5 --idx S --lr 2e-2 --split_file ~/clean_datasets/S/S_target.pkl --seed 2 --wandb-name 0510_Sr_adv_5e-7_seed2_GPU3 --adv --gamma 5e-7  > 0510_Sr_adv_5e-7_seed2_GPU1.out &

CUDA_VISIBLE_DEVICES=2 nohup python -u finetune_sup_head_regression.py esm1b_t33_650M_UR50S ~/clean_datasets/S/S_target sup --include mean per_tok --toks_per_batch 2048 --num_classes 5 --idx S --lr 2e-2 --split_file ~/clean_datasets/S/S_target.pkl --seed 1 --wandb-name 0510_Sr_adv_5e-6_seed1_GPU3 --adv --gamma 5e-6  > 0510_Sr_adv_5e-6_seed1_GPU2.out &

CUDA_VISIBLE_DEVICES=3 nohup python -u finetune_sup_head_regression.py esm1b_t33_650M_UR50S ~/clean_datasets/S/S_target sup --include mean per_tok --toks_per_batch 2048 --num_classes 5 --idx S --lr 2e-2 --split_file ~/clean_datasets/S/S_target.pkl --seed 2 --wandb-name 0510_Sr_adv_5e-6_seed2_GPU3 --adv --gamma 5e-6  > 0510_Sr_adv_5e-6_seed2_GPU3.out &

CUDA_VISIBLE_DEVICES=4 nohup python -u finetune_sup_head.py esm1b_t33_650M_UR50S ~/clean_datasets/S/S_target sup --include mean per_tok --toks_per_batch 2048 --num_classes 5 --idx S --lr 2e-2 --split_file ~/clean_datasets/S/S_classification_target.pkl --seed 1 --wandb-name 0510_S_adv_5e-7_seed1_GPU2 --adv --gamma 5e-7  > 0510_S_adv_5e-7_seed1_GPU4.out &

CUDA_VISIBLE_DEVICES=5 nohup python -u finetune_sup_head.py esm1b_t33_650M_UR50S ~/clean_datasets/S/S_target sup --include mean per_tok --toks_per_batch 2048 --num_classes 5 --idx S --lr 2e-2 --split_file ~/clean_datasets/S/S_classification_target.pkl --seed 2 --wandb-name 0510_S_adv_5e-7_seed2_GPU3 --adv --gamma 5e-7  > 0510_S_adv_5e-7_seed2_GPU5.out &

CUDA_VISIBLE_DEVICES=6 nohup python -u finetune_sup_head.py esm1b_t33_650M_UR50S ~/clean_datasets/S/S_target sup --include mean per_tok --toks_per_batch 2048 --num_classes 5 --idx S --lr 2e-2 --split_file ~/clean_datasets/S/S_classification_target.pkl --seed 1 --wandb-name 0510_S_adv_5e-6_seed1_GPU3 --adv --gamma 5e-6  > 0510_S_adv_5e-6_seed1_GPU6.out &

CUDA_VISIBLE_DEVICES=7 nohup python -u finetune_sup_head.py esm1b_t33_650M_UR50S ~/clean_datasets/S/S_target sup --include mean per_tok --toks_per_batch 2048 --num_classes 5 --idx S --lr 2e-2 --split_file ~/clean_datasets/S/S_classification_target.pkl --seed 2 --wandb-name 0510_S_adv_5e-6_seed2_GPU3 --adv --gamma 5e-6  > 0510_S_adv_5e-6_seed2_GPU7.out &